name: Update Conversion Rate

on:
  schedule:
    - cron: '0 18 * * *'  # Schedule to run at 3:00 AM every day

jobs:
  update_conversion_rate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Python Script
        run: python main.py  

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add conversion_rate.json
          git commit -m "Update conversion_rate.json"
          git push